
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        
 <style>
      table,
      th,
      td {
        padding: 10px;
        border: 1px solid black;
        border-collapse: collapse;
      }
 </style><!-- comment -->        
    </head>
    <body>
        <h2>Select Items from Cart :</h2>
        <form ACTION="">
            <table>
                <tr>
                    <td><input type="checkbox" name="id" value="0"></td>
                    <td><img src="assets\book99-450x300.jpg" alt=""  width="90" height="60"></td>
                    <td>Book 1</td>
                    <td>P120.00</td>
                    <td>1 Item</td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="id" value="1"></td>
                    <td><img src="assets\book99-450x300.jpg" alt=""  width="90" height="60"></td>
                    <td>Book 2</td>
                    <td>P150.00</td>
                    <td>1 Item</td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="id" value="2"></td>
                    <td><img src="assets\book99-450x300.jpg" alt=""  width="90" height="60"></td>
                    <td>Book 3</td>
                    <td>P210.00</td>
                    <td>1 Item</td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="id" value="3"></td>
                    <td><img src="assets\book99-450x300.jpg" alt=""  width="90" height="60"></td>
                    <td>Book 4</td>
                    <td>P130.00</td>
                    <td>1 Item</td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="id" value="4"></td>
                    <td><img src="assets\book99-450x300.jpg" alt=""  width="90" height="60"></td>
                    <td>Book 5</td>
                    <td>P180.00</td>
                    <td>1 Item</td>
                </tr>
            </table>            
            <td><input type="submit" value="Select Items"></td>
        </form>
        
        <!-- start table containing out of stock items -->
        <!-- end table containing out of stock items -->
        
        <%
            //table of values from cart depending on books, this will be generated by servlet
            float[] array = {120.0f, 150.0f, 210.0f, 130.0f, 180.0f};
            
            String s[] = request.getParameterValues("id");
            if (s != null && s.length != 0) {
                out.println("<h2>You have selected " + s.length + " items.</h2>");
                float total = 0.0f;
                for (int i = 0; i < s.length; i++) {
                    int id = Integer.valueOf(s[i]);
                    total += array[id];
                    if (i > 0) out.println(",");
                    out.println("P" + array[i]);
                }
                out.println("<h2>Total Amount P" + total + "</h2>");
        %> 
            <br>
            <a href="CheckoutServlet.do"><button>Pay now</button></a> 
        <%
            }
        %> 
        
    </body>
</html>



